
ErlOpts = [].

[
    {require_min_otp_vsn, "18"},
    
    {erl_first_files, []},
    
    {erl_opts, ErlOpts},
    {edoc_opts,[{todo,true}]},

    {eunit_opts, [verbose, {report,{eunit_surefire,[{dir,"."}]}}]},

    {cover_export_enabled, true},
    {cover_enabled, true},
    {cover_print_enable, true},

    {plugins, [rebar_covertool]},

    {covertool_eunit, {".eunit/cover.coverdata", "eunit.coverage.xml"}},
    {covertool_prefix_len, 0},
    
	{xref_warnings, false},
	{xref_checks, [undefined_function_calls, undefined_functions,
	               locals_not_used, exports_not_used,
	               deprecated_function_calls, deprecated_functions]},

	%%{deps, [
	%%    {rebar_dialyzer_plugin, ".*",
	%%      {git, "https://github.com/andrzejsliwa/rebar_dialyzer_plugin.git"}
	%%    }
	%%]},
	%%
	%%%% Plugin usage
	%%{rebar_plugins, [rebar_dialyzer_plugin]},

    {dialyzer,
		 [
		  %% Store PLT locally inside the project in .rebar (Default)
		  %% {plt_location, local},
		  %% Store PLT in custom directory
		  %% {plt_location, "custom_dir"},
		  %% Extra apps to include in the PLT
		  %% {plt_extra_apps, [app1, app2]},
		  {warnings, [unmatched_returns, error_handling]}
		 ]}
].

